src/KontorsprylarAB/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using KontorsprylarAB.Models;
using Microsoft.AspNetCore.Http;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace KontorsprylarAB.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        UserManager<IdentityUser> userManager;
        SignInManager<IdentityUser> signInManager;
        IdentityDbContext identityContext;

        public AdminController(
            UserManager<IdentityUser> userManager,
            SignInManager<IdentityUser> signInManager,
            IdentityDbContext identityContext)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
            this.identityContext = identityContext;
        }

        [AllowAnonymous]
        public IActionResult Index()
        {
            if (HttpContext.User.Identity.IsAuthenticated)
            {
                return RedirectToAction("AddProduct");
            }
            else
            {
                return RedirectToAction("Login");
            }
        }

        [AllowAnonymous]
        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        public async Task<IActionResult> Login(AccountLoginVM viewModel, string returnUrl)
        {
            if (!ModelState.IsValid)
                return View(viewModel);

            // Skapa DB-schemat
            //await identityContext.Database.EnsureCreatedAsync();

            // Create user
            //var user = new IdentityUser("admin");
            //var result = await userManager.CreateAsync(user, "Pencil69!");

            var result = await signInManager.PasswordSignInAsync(
                viewModel.Username, viewModel.Password, false, false);

            if (!result.Succeeded)
            {
                ModelState.AddModelError(nameof(AccountLoginVM.Username),
                    "Incorrect login credentials");
                return View(viewModel);
            }

            if (string.IsNullOrWhiteSpace(returnUrl))
                return RedirectToAction(nameof(AdminController.Index));
            else
                return Redirect(returnUrl);
        }

        [HttpPost]
        public IActionResult AddProduct(AddProductVM viewModel)
        {
            if (!ModelState.IsValid)
                return View(viewModel);

            DataBaseTools.AddProduct(viewModel);
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public IActionResult AddProduct()
        {
            return View();
        }
    }
}

src/KontorsprylarAB/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace KontorsprylarAB.Controllers
{
    public class ProductsController : Controller
    {
        // GET: /<controller>/
        public IActionResult View(int id)
        {
            return View(DataBaseTools.GetSpecifiedProduct(id));
        }

        public IActionResult Products(int id)
        {
            return View(DataBaseTools.GetAllProducts(id));
        }

    }
}

src/KontorsprylarAB/Controllers/UserController.cs
using KontorsprylarAB.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace KontorsprylarAB.Controllers
{
    public class UserController : Controller
    {
        IMemoryCache cache;

        public UserController(IMemoryCache cache)
        {
            this.cache = cache;
        }

        public IActionResult ShoppingCart()
        {
            var list = Models.ShoppingCart.GetShoppingCartList(HttpContext);

            return View(list);
        }

        public IActionResult AddToCart()
        {
            var item = new ShoppingItem(DataBaseTools.GetSpecifiedProduct(2), 1);

            Models.ShoppingCart.addToShoppingCart(item, this.HttpContext);

            return Redirect("Index");
        }
    }
}

src/KontorsprylarAB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>


    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <style>
    /* Remove the navbar's default margin-bottom and rounded borders */
    .navbar {
      margin-bottom: 0;
      border-radius: 0;
    }

    /* Add a gray background color and some padding to the footer */
    footer {
      background-color: #f2f2f2;
      padding: 25px;
    }

  .carousel-inner img {
      width: 100%; /* Set width to 100% */
      margin: auto;
      min-height:200px;
  }

  .col-sm-5 {
      float: none;
      
  }


  .col-sm-4 {
      height: 340px;
  }

  h2
  {
      color:crimson;
  }


  }
    </style>

        <div id="myCarousel" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
            </ol>

            <!-- Wrapper for slides -->
            <div class="carousel-inner" role="listbox">
                <div class="item active">
                    <img src="https://placehold.it/1200x400?text=Kontorsprylar AB" alt="Image">
                    <div class="carousel-caption">
                        <h3>Sell $</h3>
                        <p>Money Money.</p>
                    </div>
                </div>

                <div class="item">
                    <img src="https://placehold.it/1200x400?text=$$$" alt="Image">
                    <div class="carousel-caption">
                        <h3>More Sell $</h3>
                        <p>Lorem ipsum...</p>
                    </div>
                </div>
            </div>



            <!-- Left and right controls -->
            <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>

    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">KAB</a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    <li class="active"><a asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-controller="Products" asp-action="Products/1">Jobbkontoret</a></li>
                    <li><a asp-controller="Products" asp-action="Products/2">Hemmakontoret</a></li>
                    <li><a asp-controller="Admin" asp-action="Index">Admin</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a asp-controller="User" asp-action="ShoppingCart"><img src="https://cdn0.iconfinder.com/data/icons/shopping-extras-set-1/512/21-512.png" height="30"></a></li>
                    <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                </ul>
            </div>
        </div>
    </nav>



        @RenderBody()

        <footer class="container-fluid text-center">
            <p>Kontorsprylar AB</p>
        </footer>



    </body>
</html>